let a = typeof 37 === 'number';
let b = typeof 3.14 === 'number';
let c = typeof pi === 'undefined';
let d = typeof Symbol('foo') === 'symbol';
let e = typeof false === 'boolean';
let f = typeof Number('Test') === 'number';
let g = typeof "" === 'string';
let h = typeof "Udemy" === 'string';
let i = typeof Infinity === 'number';
let j = typeof (typeof 1) === 'string';
let k = typeof String(3.14) === 'string';
let l = typeof true === 'boolean';
let m = typeof Boolean("") === 'boolean';
let n = typeof Symbol() === 'symbol';
let o = typeof NaN === 'number';
let p = typeof Symbol.iterator === 'symbol';
let q = typeof undefined === 'undefined';
let r = typeof "3.14" === 'string';
let s = typeof [1, 2, 3] === 'object';
let t = typeof Math.sin === 'function';